import Head from 'next/head';
// import Image from 'next/image';
// import Script from 'next/script'
import AboutMeSection from '../components/AboutMeSection';
import HomeSection from '../components/HomeSection';
import ProjectSection from '../components/ProjectSection';
import NavbarHome from '../components/NavbarHome';
import ContactSection from '../components/ContactSection';
import Footer from '../components/Footer';

export default function Home() {
  return (
    <div>
      <Head>
        <title>DotsDizzy - Illustrator From Indonesia</title>
        <meta name="keyword" content="Generated by create next app" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <NavbarHome bgC="dark" variant="dark" fluid={true}/>
      </header>
      <main>
        <section id="home" >
          <HomeSection/>
        </section>
        <section id="about">
          <AboutMeSection/>
        </section>
        <section id="project">
          <ProjectSection/>
        </section>
        <section id="contact">
          <ContactSection/>
        </section>
      </main>


      <footer >
        <Footer/>
      </footer>
      {/* <Script
        id="boxicon-js"
        src="https://unpkg.com/boxicons@2.0.9/dist/boxicons.js"
      /> */}
    </div>
  )
}
